// Generated by scripts/export_engine_data.py from the Python engine. Do not edit.
/* eslint-disable */
(function(g){g.QCW_DATA={
 "arabic_lures": {
  "استرداد": "refund",
  "المدنيه": "civil",
  "الهويه": "identity",
  "امن": "secure",
  "بطاقه": "card",
  "بنك": "bank",
  "تاكيد": "confirm",
  "تحديث": "update",
  "تحويل": "transfer",
  "تسجيل": "register",
  "تفعيل": "activate",
  "توصيل": "delivery",
  "جايزه": "prize",
  "حساب": "account",
  "حكومه": "government",
  "دخول": "login",
  "دفع": "pay",
  "رمز": "code",
  "شحنه": "shipment",
  "عاجل": "urgent",
  "عرض": "offer",
  "غرامه": "fine",
  "كلمه المرور": "password",
  "مجاني": "free",
  "مخالفه": "violation",
  "مكافاه": "reward",
  "هديه": "gift"
 },
 "brands": [
  {
   "alias_labels": [
    "qnbbank",
    "qnbgroup",
    "qnbonline"
   ],
   "aliases": [
    "qnbonline",
    "qnbbank",
    "qnbgroup"
   ],
   "arabic_keywords": [
    "بنك قطر الوطني",
    "قطر الوطني"
   ],
   "arabic_normalized": [
    "بنك قطر الوطني",
    "قطر الوطني"
   ],
   "domains": [
    "qnb.com",
    "qnb.com.qa"
   ],
   "industry": "banking",
   "keywords": [
    "qnb",
    "qatar national bank",
    "qnb group"
   ],
   "name": "Qatar National Bank (QNB)",
   "phrases": [
    [
     "qatar",
     "national",
     "bank"
    ],
    [
     "qnb",
     "group"
    ]
   ],
   "primary_labels": [
    "qnb"
   ],
   "priority": "critical",
   "short_name": "QNB"
  },
  {
   "alias_labels": [
    "cbqonline",
    "commercialbank",
    "commercialbankqatar"
   ],
   "aliases": [
    "cbqonline",
    "commercialbankqatar"
   ],
   "arabic_keywords": [
    "البنك التجاري",
    "البنك التجاري القطري"
   ],
   "arabic_normalized": [
    "البنك التجاري",
    "البنك التجاري القطري"
   ],
   "domains": [
    "cbq.qa"
   ],
   "industry": "banking",
   "keywords": [
    "cbq",
    "commercial bank of qatar",
    "commercialbank"
   ],
   "name": "Commercial Bank of Qatar (CBQ)",
   "phrases": [
    [
     "commercial",
     "bank",
     "of",
     "qatar"
    ]
   ],
   "primary_labels": [
    "cbq"
   ],
   "priority": "critical",
   "short_name": "CBQ"
  },
  {
   "alias_labels": [
    "dohabankonline"
   ],
   "aliases": [
    "dohabankonline"
   ],
   "arabic_keywords": [
    "بنك الدوحة"
   ],
   "arabic_normalized": [
    "بنك الدوحه"
   ],
   "domains": [
    "dohabank.com",
    "dohabank.qa"
   ],
   "industry": "banking",
   "keywords": [
    "dohabank",
    "doha bank"
   ],
   "name": "Doha Bank",
   "phrases": [
    [
     "doha",
     "bank"
    ]
   ],
   "primary_labels": [
    "dohabank"
   ],
   "priority": "critical",
   "short_name": "Doha Bank"
  },
  {
   "alias_labels": [
    "qibbank",
    "qibonline"
   ],
   "aliases": [
    "qibonline",
    "qibbank"
   ],
   "arabic_keywords": [
    "مصرف قطر الإسلامي",
    "قطر الإسلامي"
   ],
   "arabic_normalized": [
    "مصرف قطر الاسلامي",
    "قطر الاسلامي"
   ],
   "domains": [
    "qib.com.qa"
   ],
   "industry": "banking",
   "keywords": [
    "qib",
    "qatar islamic bank"
   ],
   "name": "Qatar Islamic Bank (QIB)",
   "phrases": [
    [
     "qatar",
     "islamic",
     "bank"
    ]
   ],
   "primary_labels": [
    "qib"
   ],
   "priority": "critical",
   "short_name": "QIB"
  },
  {
   "alias_labels": [
    "alrayanbank",
    "masrafalrayan",
    "rayanbank"
   ],
   "aliases": [
    "alrayanbank",
    "rayanbank"
   ],
   "arabic_keywords": [
    "مصرف الريان",
    "الريان"
   ],
   "arabic_normalized": [
    "مصرف الريان",
    "الريان"
   ],
   "domains": [
    "alrayan.com"
   ],
   "industry": "banking",
   "keywords": [
    "alrayan",
    "al rayan",
    "masraf al rayan",
    "masrafalrayan"
   ],
   "name": "Masraf Al Rayan",
   "phrases": [
    [
     "al",
     "rayan"
    ],
    [
     "masraf",
     "al",
     "rayan"
    ]
   ],
   "primary_labels": [
    "alrayan"
   ],
   "priority": "critical",
   "short_name": "Al Rayan"
  },
  {
   "alias_labels": [
    "dukhan",
    "dukhanonline"
   ],
   "aliases": [
    "dukhanonline"
   ],
   "arabic_keywords": [
    "بنك دخان",
    "دخان"
   ],
   "arabic_normalized": [
    "بنك دخان",
    "دخان"
   ],
   "domains": [
    "dukhanbank.com"
   ],
   "industry": "banking",
   "keywords": [
    "dukhan",
    "dukhan bank",
    "dukhanbank"
   ],
   "name": "Dukhan Bank",
   "phrases": [
    [
     "dukhan",
     "bank"
    ]
   ],
   "primary_labels": [
    "dukhanbank"
   ],
   "priority": "critical",
   "short_name": "Dukhan Bank"
  },
  {
   "alias_labels": [
    "ahlibankqa",
    "ahlibankqatar",
    "ahlionline"
   ],
   "aliases": [
    "ahlibankqa",
    "ahlionline"
   ],
   "arabic_keywords": [
    "البنك الأهلي",
    "الأهلي القطري"
   ],
   "arabic_normalized": [
    "البنك الاهلي",
    "الاهلي القطري"
   ],
   "domains": [
    "ahlibank.com.qa"
   ],
   "industry": "banking",
   "keywords": [
    "ahlibank",
    "ahli bank qatar",
    "ahlibankqatar"
   ],
   "name": "Ahlibank Qatar",
   "phrases": [
    [
     "ahli",
     "bank",
     "qatar"
    ]
   ],
   "primary_labels": [
    "ahlibank"
   ],
   "priority": "high",
   "short_name": "Ahlibank"
  },
  {
   "alias_labels": [
    "qiibonline"
   ],
   "aliases": [
    "qiibonline"
   ],
   "arabic_keywords": [
    "الدولي الإسلامي",
    "مصرف قطر الدولي الإسلامي"
   ],
   "arabic_normalized": [
    "الدولي الاسلامي",
    "مصرف قطر الدولي الاسلامي"
   ],
   "domains": [
    "qiib.com.qa"
   ],
   "industry": "banking",
   "keywords": [
    "qiib",
    "qatar international islamic bank",
    "international islamic"
   ],
   "name": "Qatar International Islamic Bank (QIIB)",
   "phrases": [
    [
     "qatar",
     "international",
     "islamic",
     "bank"
    ],
    [
     "international",
     "islamic"
    ]
   ],
   "primary_labels": [
    "qiib"
   ],
   "priority": "critical",
   "short_name": "QIIB"
  },
  {
   "alias_labels": [
    "qdbqatar"
   ],
   "aliases": [
    "qdbqatar"
   ],
   "arabic_keywords": [
    "بنك قطر للتنمية"
   ],
   "arabic_normalized": [
    "بنك قطر للتنميه"
   ],
   "domains": [
    "qdb.qa"
   ],
   "industry": "banking",
   "keywords": [
    "qdb",
    "qatar development bank"
   ],
   "name": "Qatar Development Bank (QDB)",
   "phrases": [
    [
     "qatar",
     "development",
     "bank"
    ]
   ],
   "primary_labels": [
    "qdb"
   ],
   "priority": "high",
   "short_name": "QDB"
  },
  {
   "alias_labels": [
    "qcbgov",
    "qcbonline"
   ],
   "aliases": [
    "qcbgov",
    "qcbonline"
   ],
   "arabic_keywords": [
    "مصرف قطر المركزي",
    "قطر المركزي"
   ],
   "arabic_normalized": [
    "مصرف قطر المركزي",
    "قطر المركزي"
   ],
   "domains": [
    "qcb.gov.qa"
   ],
   "industry": "banking",
   "keywords": [
    "qcb",
    "qatar central bank",
    "central bank of qatar"
   ],
   "name": "Qatar Central Bank (QCB)",
   "phrases": [
    [
     "qatar",
     "central",
     "bank"
    ],
    [
     "central",
     "bank",
     "of",
     "qatar"
    ]
   ],
   "primary_labels": [
    "qcb"
   ],
   "priority": "critical",
   "short_name": "QCB"
  },
  {
   "alias_labels": [
    "qfcqatar"
   ],
   "aliases": [
    "qfcqatar"
   ],
   "arabic_keywords": [
    "مركز قطر للمال"
   ],
   "arabic_normalized": [
    "مركز قطر للمال"
   ],
   "domains": [
    "qfc.qa",
    "qfcra.com"
   ],
   "industry": "finance",
   "keywords": [
    "qfc",
    "qatar financial centre",
    "qatar financial center",
    "qfcra"
   ],
   "name": "Qatar Financial Centre (QFC)",
   "phrases": [
    [
     "qatar",
     "financial",
     "centre"
    ],
    [
     "qatar",
     "financial",
     "center"
    ]
   ],
   "primary_labels": [
    "qfc",
    "qfcra"
   ],
   "priority": "medium",
   "short_name": "QFC"
  },
  {
   "alias_labels": [
    "himyan",
    "himyancard",
    "himyanpay",
    "naps",
    "napsqatar"
   ],
   "aliases": [
    "himyancard",
    "himyanpay"
   ],
   "arabic_keywords": [
    "حميان",
    "بطاقة حميان"
   ],
   "arabic_normalized": [
    "حميان",
    "بطاقه حميان"
   ],
   "domains": [],
   "industry": "payments",
   "keywords": [
    "himyan",
    "himyan card",
    "naps",
    "napsqatar",
    "national atm and pos switch"
   ],
   "name": "Himyan card scheme and NAPS switch (QCB)",
   "phrases": [
    [
     "himyan",
     "card"
    ],
    [
     "national",
     "atm",
     "and",
     "pos",
     "switch"
    ]
   ],
   "primary_labels": [],
   "priority": "critical",
   "short_name": "Himyan"
  },
  {
   "alias_labels": [
    "sadadpay",
    "sadadqa",
    "sadadqatar"
   ],
   "aliases": [
    "sadadpay",
    "sadadqa"
   ],
   "arabic_keywords": [
    "سداد"
   ],
   "arabic_normalized": [
    "سداد"
   ],
   "domains": [
    "sadad.qa"
   ],
   "industry": "payments",
   "keywords": [
    "sadad",
    "sadad qatar",
    "sadadqatar"
   ],
   "name": "Sadad Qatar",
   "phrases": [
    [
     "sadad",
     "qatar"
    ]
   ],
   "primary_labels": [
    "sadad"
   ],
   "priority": "critical",
   "short_name": "Sadad"
  },
  {
   "alias_labels": [
    "myooredoo",
    "ooredoomoney",
    "ooredooqa"
   ],
   "aliases": [
    "ooredooqa",
    "ooredoo-qa",
    "myooredoo"
   ],
   "arabic_keywords": [
    "أوريدو",
    "أوريدو قطر",
    "اوريدو"
   ],
   "arabic_normalized": [
    "اوريدو",
    "اوريدو قطر",
    "اوريدو"
   ],
   "domains": [
    "ooredoo.qa",
    "ooredoo.com"
   ],
   "industry": "telecom",
   "keywords": [
    "ooredoo",
    "ooredoo qatar",
    "ooredoo money",
    "ooredoomoney"
   ],
   "name": "Ooredoo Qatar",
   "phrases": [
    [
     "ooredoo",
     "qatar"
    ],
    [
     "ooredoo",
     "money"
    ]
   ],
   "primary_labels": [
    "ooredoo"
   ],
   "priority": "critical",
   "short_name": "Ooredoo"
  },
  {
   "alias_labels": [
    "myvodafoneqa",
    "vodafoneqa",
    "vodafoneqatar"
   ],
   "aliases": [
    "myvodafoneqa"
   ],
   "arabic_keywords": [
    "فودافون قطر",
    "فودافون"
   ],
   "arabic_normalized": [
    "فودافون قطر",
    "فودافون"
   ],
   "domains": [
    "vodafone.qa",
    "vodafone.com"
   ],
   "industry": "telecom",
   "keywords": [
    "vodafone qatar",
    "vodafoneqatar",
    "vodafone-qa",
    "vodafoneqa"
   ],
   "name": "Vodafone Qatar",
   "phrases": [
    [
     "vodafone",
     "qatar"
    ]
   ],
   "primary_labels": [
    "vodafone"
   ],
   "priority": "critical",
   "short_name": "Vodafone Qatar"
  },
  {
   "alias_labels": [
    "hukoomigov",
    "hukoomiqatar"
   ],
   "aliases": [
    "hukoomiqatar",
    "hukoomi-gov"
   ],
   "arabic_keywords": [
    "حكومي",
    "بوابة حكومي"
   ],
   "arabic_normalized": [
    "حكومي",
    "بوابه حكومي"
   ],
   "domains": [
    "hukoomi.gov.qa"
   ],
   "industry": "government",
   "keywords": [
    "hukoomi",
    "hukoomi portal",
    "qatar e-government",
    "qatar egov"
   ],
   "name": "Hukoomi (Qatar e-Government portal)",
   "phrases": [
    [
     "hukoomi",
     "portal"
    ],
    [
     "qatar",
     "e-government"
    ],
    [
     "qatar",
     "egov"
    ]
   ],
   "primary_labels": [
    "hukoomi"
   ],
   "priority": "critical",
   "short_name": "Hukoomi"
  },
  {
   "alias_labels": [
    "metrash",
    "metrash2",
    "metrash2app",
    "moigovqa",
    "moiqa",
    "moiqatar",
    "qatarid"
   ],
   "aliases": [
    "moigovqa",
    "metrash2app"
   ],
   "arabic_keywords": [
    "وزارة الداخلية",
    "مطراش",
    "البطاقة الشخصية"
   ],
   "arabic_normalized": [
    "وزاره الداخليه",
    "مطراش",
    "البطاقه الشخصيه"
   ],
   "domains": [
    "moi.gov.qa"
   ],
   "industry": "government",
   "keywords": [
    "moi qatar",
    "moi-qa",
    "moiqatar",
    "metrash",
    "metrash2",
    "ministry of interior qatar",
    "qatar id",
    "qatarid"
   ],
   "name": "Ministry of Interior Qatar (MOI) and Metrash",
   "phrases": [
    [
     "moi",
     "qatar"
    ],
    [
     "ministry",
     "of",
     "interior",
     "qatar"
    ],
    [
     "qatar",
     "id"
    ]
   ],
   "primary_labels": [
    "moi"
   ],
   "priority": "critical",
   "short_name": "MOI"
  },
  {
   "alias_labels": [
    "ncsaqatar",
    "qcertqatar"
   ],
   "aliases": [
    "ncsaqatar",
    "qcertqatar"
   ],
   "arabic_keywords": [
    "الوكالة الوطنية للأمن السيبراني",
    "الأمن السيبراني"
   ],
   "arabic_normalized": [
    "الوكاله الوطنيه للامن السيبراني",
    "الامن السيبراني"
   ],
   "domains": [
    "ncsa.gov.qa",
    "qcert.org"
   ],
   "industry": "government",
   "keywords": [
    "ncsa",
    "ncsa qatar",
    "qcert",
    "q-cert",
    "national cyber security agency"
   ],
   "name": "National Cyber Security Agency (NCSA) and Q-CERT",
   "phrases": [
    [
     "ncsa",
     "qatar"
    ],
    [
     "national",
     "cyber",
     "security",
     "agency"
    ]
   ],
   "primary_labels": [
    "ncsa",
    "qcert"
   ],
   "priority": "high",
   "short_name": "NCSA"
  },
  {
   "alias_labels": [
    "mophqa",
    "mophqatar"
   ],
   "aliases": [
    "mophqa"
   ],
   "arabic_keywords": [
    "وزارة الصحة",
    "وزارة الصحة العامة"
   ],
   "arabic_normalized": [
    "وزاره الصحه",
    "وزاره الصحه العامه"
   ],
   "domains": [
    "moph.gov.qa"
   ],
   "industry": "government",
   "keywords": [
    "moph",
    "moph qatar",
    "mophqatar",
    "ministry of public health"
   ],
   "name": "Ministry of Public Health (MOPH)",
   "phrases": [
    [
     "moph",
     "qatar"
    ],
    [
     "ministry",
     "of",
     "public",
     "health"
    ]
   ],
   "primary_labels": [
    "moph"
   ],
   "priority": "high",
   "short_name": "MOPH"
  },
  {
   "alias_labels": [
    "hamadhospital",
    "hamadmedical",
    "hmcqa",
    "hmcqatar"
   ],
   "aliases": [
    "hamadhospital",
    "hmcqa"
   ],
   "arabic_keywords": [
    "مؤسسة حمد الطبية",
    "حمد الطبية"
   ],
   "arabic_normalized": [
    "موسسه حمد الطبيه",
    "حمد الطبيه"
   ],
   "domains": [
    "hamad.qa"
   ],
   "industry": "healthcare",
   "keywords": [
    "hamad medical",
    "hamadmedical",
    "hmc qatar",
    "hmcqatar"
   ],
   "name": "Hamad Medical Corporation (HMC)",
   "phrases": [
    [
     "hamad",
     "medical"
    ],
    [
     "hmc",
     "qatar"
    ]
   ],
   "primary_labels": [
    "hamad"
   ],
   "priority": "high",
   "short_name": "HMC"
  },
  {
   "alias_labels": [
    "mcitqa",
    "mcitqatar"
   ],
   "aliases": [
    "mcitqa"
   ],
   "arabic_keywords": [
    "وزارة الاتصالات",
    "وزارة الاتصالات وتكنولوجيا المعلومات"
   ],
   "arabic_normalized": [
    "وزاره الاتصالات",
    "وزاره الاتصالات وتكنولوجيا المعلومات"
   ],
   "domains": [
    "mcit.gov.qa"
   ],
   "industry": "government",
   "keywords": [
    "mcit",
    "mcit qatar",
    "mcitqatar",
    "ministry of communications"
   ],
   "name": "Ministry of Communications and Information Technology (MCIT)",
   "phrases": [
    [
     "mcit",
     "qatar"
    ],
    [
     "ministry",
     "of",
     "communications"
    ]
   ],
   "primary_labels": [
    "mcit"
   ],
   "priority": "high",
   "short_name": "MCIT"
  },
  {
   "alias_labels": [
    "mociqa",
    "mociqatar"
   ],
   "aliases": [
    "mociqa"
   ],
   "arabic_keywords": [
    "وزارة التجارة",
    "وزارة التجارة والصناعة"
   ],
   "arabic_normalized": [
    "وزاره التجاره",
    "وزاره التجاره والصناعه"
   ],
   "domains": [
    "moci.gov.qa"
   ],
   "industry": "government",
   "keywords": [
    "moci",
    "moci qatar",
    "mociqatar",
    "ministry of commerce"
   ],
   "name": "Ministry of Commerce and Industry (MOCI)",
   "phrases": [
    [
     "moci",
     "qatar"
    ],
    [
     "ministry",
     "of",
     "commerce"
    ]
   ],
   "primary_labels": [
    "moci"
   ],
   "priority": "medium",
   "short_name": "MOCI"
  },
  {
   "alias_labels": [
    "kahramaapay",
    "kahramaaqa"
   ],
   "aliases": [
    "kahramaapay",
    "kahramaaqa"
   ],
   "arabic_keywords": [
    "كهرماء",
    "المؤسسة العامة القطرية للكهرباء والماء"
   ],
   "arabic_normalized": [
    "كهرماء",
    "الموسسه العامه القطريه للكهرباء والماء"
   ],
   "domains": [
    "km.qa",
    "kahramaa.qa"
   ],
   "industry": "energy",
   "keywords": [
    "kahramaa",
    "kahramaa bill",
    "qatar electricity and water"
   ],
   "name": "Kahramaa (Qatar General Electricity and Water Corporation)",
   "phrases": [
    [
     "kahramaa",
     "bill"
    ],
    [
     "qatar",
     "electricity",
     "and",
     "water"
    ]
   ],
   "primary_labels": [
    "kahramaa"
   ],
   "priority": "high",
   "short_name": "Kahramaa"
  },
  {
   "alias_labels": [
    "ashghalqa"
   ],
   "aliases": [
    "ashghalqa"
   ],
   "arabic_keywords": [
    "أشغال",
    "هيئة الأشغال العامة"
   ],
   "arabic_normalized": [
    "اشغال",
    "هييه الاشغال العامه"
   ],
   "domains": [
    "ashghal.gov.qa"
   ],
   "industry": "government",
   "keywords": [
    "ashghal",
    "public works authority qatar"
   ],
   "name": "Ashghal (Public Works Authority)",
   "phrases": [
    [
     "public",
     "works",
     "authority",
     "qatar"
    ]
   ],
   "primary_labels": [
    "ashghal"
   ],
   "priority": "medium",
   "short_name": "Ashghal"
  },
  {
   "alias_labels": [
    "qatarenergyqa",
    "qatarpetroleum"
   ],
   "aliases": [
    "qatarenergyqa"
   ],
   "arabic_keywords": [
    "قطر للطاقة",
    "قطر للبترول"
   ],
   "arabic_normalized": [
    "قطر للطاقه",
    "قطر للبترول"
   ],
   "domains": [
    "qatarenergy.qa",
    "qp.com.qa"
   ],
   "industry": "energy",
   "keywords": [
    "qatarenergy",
    "qatar energy",
    "qatar petroleum",
    "qatarpetroleum"
   ],
   "name": "QatarEnergy",
   "phrases": [
    [
     "qatar",
     "energy"
    ],
    [
     "qatar",
     "petroleum"
    ]
   ],
   "primary_labels": [
    "qatarenergy"
   ],
   "priority": "high",
   "short_name": "QatarEnergy"
  },
  {
   "alias_labels": [
    "privilegedub",
    "qatarair",
    "qatarairway",
    "qrairways"
   ],
   "aliases": [
    "qrairways",
    "qatarair"
   ],
   "arabic_keywords": [
    "القطرية",
    "الخطوط الجوية القطرية",
    "نادي الامتياز"
   ],
   "arabic_normalized": [
    "القطريه",
    "الخطوط الجويه القطريه",
    "نادي الامتياز"
   ],
   "domains": [
    "qatarairways.com",
    "qatarairways.com.qa"
   ],
   "industry": "aviation",
   "keywords": [
    "qatar airways",
    "qatarairways",
    "qatarairway",
    "qatar-airways",
    "privilege club",
    "privilegeclub"
   ],
   "name": "Qatar Airways",
   "phrases": [
    [
     "qatar",
     "airways"
    ],
    [
     "privilege",
     "club"
    ]
   ],
   "primary_labels": [
    "qatarairways"
   ],
   "priority": "critical",
   "short_name": "Qatar Airways"
  },
  {
   "alias_labels": [
    "hamadairport",
    "hiaqatar"
   ],
   "aliases": [
    "hiaqatar",
    "hamad-airport"
   ],
   "arabic_keywords": [
    "مطار حمد الدولي",
    "مطار حمد"
   ],
   "arabic_normalized": [
    "مطار حمد الدولي",
    "مطار حمد"
   ],
   "domains": [
    "dohahamadairport.com"
   ],
   "industry": "aviation",
   "keywords": [
    "hamad international airport",
    "hamadairport",
    "dohahamadairport",
    "doha airport"
   ],
   "name": "Hamad International Airport (HIA)",
   "phrases": [
    [
     "hamad",
     "international",
     "airport"
    ],
    [
     "doha",
     "airport"
    ]
   ],
   "primary_labels": [
    "dohahamadairport"
   ],
   "priority": "medium",
   "short_name": "HIA"
  },
  {
   "alias_labels": [
    "qatarpost",
    "qpostdelivery",
    "qpostqa"
   ],
   "aliases": [
    "qpostqa",
    "qpostdelivery"
   ],
   "arabic_keywords": [
    "بريد قطر",
    "البريد القطري"
   ],
   "arabic_normalized": [
    "بريد قطر",
    "البريد القطري"
   ],
   "domains": [
    "qpost.qa"
   ],
   "industry": "government",
   "keywords": [
    "qpost",
    "qatar post",
    "qatarpost"
   ],
   "name": "Qatar Post (Qpost)",
   "phrases": [
    [
     "qatar",
     "post"
    ]
   ],
   "primary_labels": [
    "qpost"
   ],
   "priority": "high",
   "short_name": "Qatar Post"
  },
  {
   "alias_labels": [
    "qatarcharity",
    "qcharityqa"
   ],
   "aliases": [
    "qcharityqa"
   ],
   "arabic_keywords": [
    "قطر الخيرية"
   ],
   "arabic_normalized": [
    "قطر الخيريه"
   ],
   "domains": [
    "qcharity.org"
   ],
   "industry": "charity",
   "keywords": [
    "qatar charity",
    "qatarcharity",
    "qcharity"
   ],
   "name": "Qatar Charity",
   "phrases": [
    [
     "qatar",
     "charity"
    ]
   ],
   "primary_labels": [
    "qcharity"
   ],
   "priority": "medium",
   "short_name": "Qatar Charity"
  },
  {
   "alias_labels": [
    "qatarredcrescent",
    "qrcsqatar"
   ],
   "aliases": [
    "qrcsqatar"
   ],
   "arabic_keywords": [
    "الهلال الأحمر القطري"
   ],
   "arabic_normalized": [
    "الهلال الاحمر القطري"
   ],
   "domains": [
    "qrcs.org.qa"
   ],
   "industry": "charity",
   "keywords": [
    "qatar red crescent",
    "qatarredcrescent",
    "qrcs"
   ],
   "name": "Qatar Red Crescent Society (QRCS)",
   "phrases": [
    [
     "qatar",
     "red",
     "crescent"
    ]
   ],
   "primary_labels": [
    "qrcs"
   ],
   "priority": "medium",
   "short_name": "QRCS"
  },
  {
   "alias_labels": [
    "snoonuapp",
    "snoonuqa"
   ],
   "aliases": [
    "snoonuqa",
    "snoonuapp"
   ],
   "arabic_keywords": [
    "سنونو"
   ],
   "arabic_normalized": [
    "سنونو"
   ],
   "domains": [
    "snoonu.com"
   ],
   "industry": "ecommerce",
   "keywords": [
    "snoonu"
   ],
   "name": "Snoonu",
   "phrases": [],
   "primary_labels": [
    "snoonu"
   ],
   "priority": "medium",
   "short_name": "Snoonu"
  },
  {
   "alias_labels": [
    "talabatqa"
   ],
   "aliases": [
    "talabatqa"
   ],
   "arabic_keywords": [
    "طلبات"
   ],
   "arabic_normalized": [
    "طلبات"
   ],
   "domains": [
    "talabat.com"
   ],
   "industry": "ecommerce",
   "keywords": [
    "talabat",
    "talabat qatar"
   ],
   "name": "Talabat Qatar",
   "phrases": [
    [
     "talabat",
     "qatar"
    ]
   ],
   "primary_labels": [
    "talabat"
   ],
   "priority": "medium",
   "short_name": "Talabat"
  },
  {
   "alias_labels": [
    "qataruniversity",
    "quedu",
    "quqatar"
   ],
   "aliases": [
    "quqatar"
   ],
   "arabic_keywords": [
    "جامعة قطر"
   ],
   "arabic_normalized": [
    "جامعه قطر"
   ],
   "domains": [
    "qu.edu.qa"
   ],
   "industry": "education",
   "keywords": [
    "qatar university",
    "qataruniversity",
    "qu-edu"
   ],
   "name": "Qatar University (QU)",
   "phrases": [
    [
     "qatar",
     "university"
    ]
   ],
   "primary_labels": [],
   "priority": "medium",
   "short_name": "QU"
  },
  {
   "alias_labels": [
    "educationcity",
    "qatarfoundation",
    "qfqatar"
   ],
   "aliases": [
    "qfqatar"
   ],
   "arabic_keywords": [
    "مؤسسة قطر"
   ],
   "arabic_normalized": [
    "موسسه قطر"
   ],
   "domains": [
    "qf.org.qa"
   ],
   "industry": "education",
   "keywords": [
    "qatar foundation",
    "qatarfoundation",
    "education city",
    "educationcity"
   ],
   "name": "Qatar Foundation (QF)",
   "phrases": [
    [
     "qatar",
     "foundation"
    ],
    [
     "education",
     "city"
    ]
   ],
   "primary_labels": [],
   "priority": "medium",
   "short_name": "QF"
  }
 ],
 "certstream_keywords": [
  "qatar",
  "qatari",
  "doha",
  "dohaqatar",
  "974",
  "قطر",
  "الدوحة",
  "qnb",
  "qnbonline",
  "qnbbank",
  "qnbgroup",
  "cbq",
  "cbqonline",
  "commercialbank",
  "dohabank",
  "qib",
  "qibonline",
  "alrayan",
  "masrafalrayan",
  "rayanbank",
  "dukhan",
  "dukhanbank",
  "ahlibank",
  "ahlibankqa",
  "qiib",
  "qiibonline",
  "qdb",
  "qcb",
  "qfc",
  "himyan",
  "himyanpay",
  "napsqatar",
  "naps-qa",
  "sadad",
  "sadadqa",
  "sadadqatar",
  "qpay",
  "qatarpay",
  "qa-pay",
  "qatarbank",
  "qatar-bank",
  "dohapay",
  "ooredoo",
  "ooredooqa",
  "ooredoo-qa",
  "ooredoomoney",
  "vodafoneqa",
  "vodafone-qa",
  "vodafoneqatar",
  "hukoomi",
  "metrash",
  "metrash2",
  "moi-qa",
  "moiqatar",
  "moi-gov",
  "qatarid",
  "qatar-id",
  "ncsa",
  "qcert",
  "q-cert",
  "moph",
  "mophqatar",
  "hamadmedical",
  "hmc-qa",
  "hmcqatar",
  "mcit",
  "mcitqatar",
  "moci",
  "mociqatar",
  "mme-qa",
  "ashghal",
  "kahramaa",
  "qpost",
  "qatarpost",
  "gov-qa",
  "qatargov",
  "qatar-gov",
  "e-gov-qa",
  "egov-qa",
  "qatarenergy",
  "qatarpetroleum",
  "qatarairways",
  "qatar-airways",
  "privilegeclub",
  "hamadairport",
  "dohahamadairport",
  "qcharity",
  "qatarcharity",
  "qrcs",
  "snoonu",
  "talabat",
  "qatarfoundation",
  "qataruniversity",
  "educationcity"
 ],
 "combo_keywords": [
  "5g",
  "974",
  "account",
  "accounts",
  "activate",
  "activation",
  "admin",
  "alert",
  "alerts",
  "app",
  "apps",
  "auth",
  "balance",
  "bank",
  "banking",
  "bill",
  "billing",
  "bills",
  "bonus",
  "book",
  "booking",
  "card",
  "cards",
  "career",
  "careers",
  "cashback",
  "center",
  "centre",
  "checkin",
  "civil",
  "click",
  "client",
  "cloud",
  "com",
  "confirm",
  "credit",
  "crypto",
  "customer",
  "customers",
  "data",
  "delivery",
  "deposit",
  "digital",
  "direct",
  "doha",
  "ebank",
  "ebanking",
  "email",
  "esim",
  "express",
  "fiber",
  "fine",
  "fines",
  "flight",
  "flights",
  "gcc",
  "get",
  "gift",
  "global",
  "go",
  "gov",
  "group",
  "help",
  "helpdesk",
  "hr",
  "hukoomi",
  "id",
  "info",
  "international",
  "internet",
  "investment",
  "invoice",
  "job",
  "jobs",
  "kyc",
  "link",
  "live",
  "loan",
  "loans",
  "login",
  "logon",
  "loyalty",
  "mail",
  "me",
  "miles",
  "mobile",
  "my",
  "net",
  "netbanking",
  "new",
  "notice",
  "now",
  "offer",
  "offers",
  "official",
  "online",
  "order",
  "orders",
  "org",
  "otp",
  "parcel",
  "pay",
  "payment",
  "payments",
  "plus",
  "points",
  "portal",
  "prize",
  "pro",
  "promo",
  "qa",
  "qatar",
  "recharge",
  "refund",
  "renew",
  "renewal",
  "reservation",
  "reset",
  "reward",
  "rewards",
  "sahelapp",
  "salary",
  "savings",
  "secure",
  "security",
  "service",
  "services",
  "shop",
  "signin",
  "sim",
  "smart",
  "statement",
  "stocks",
  "store",
  "support",
  "tax",
  "team",
  "the",
  "ticket",
  "tickets",
  "topup",
  "track",
  "tracking",
  "trading",
  "traffic",
  "transfer",
  "update",
  "user",
  "users",
  "validate",
  "validation",
  "verification",
  "verify",
  "verifyid",
  "visa",
  "wallet",
  "web",
  "wifi",
  "www",
  "zakat"
 ],
 "confusables": {
  "ð": "d",
  "ø": "o",
  "þ": "p",
  "đ": "d",
  "ı": "i",
  "ł": "l",
  "ƒ": "f",
  "ɑ": "a",
  "ɡ": "g",
  "ɢ": "g",
  "ɩ": "i",
  "ɪ": "i",
  "ɴ": "n",
  "ʀ": "r",
  "ʏ": "y",
  "ʙ": "b",
  "ʟ": "l",
  "α": "a",
  "β": "b",
  "γ": "y",
  "ε": "e",
  "η": "n",
  "ι": "i",
  "κ": "k",
  "μ": "u",
  "ν": "v",
  "ο": "o",
  "ρ": "p",
  "τ": "t",
  "υ": "u",
  "χ": "x",
  "ω": "w",
  "ϖ": "w",
  "ϱ": "p",
  "ϲ": "c",
  "ϳ": "j",
  "а": "a",
  "в": "b",
  "г": "r",
  "е": "e",
  "з": "z",
  "к": "k",
  "м": "m",
  "н": "h",
  "о": "o",
  "п": "n",
  "р": "p",
  "с": "c",
  "т": "t",
  "у": "y",
  "х": "x",
  "ц": "u",
  "ъ": "b",
  "ь": "b",
  "ё": "e",
  "є": "e",
  "ѕ": "s",
  "і": "i",
  "ї": "i",
  "ј": "j",
  "ѵ": "v",
  "ғ": "f",
  "ү": "y",
  "һ": "h",
  "ӏ": "l",
  "ө": "o",
  "ԁ": "d",
  "ԛ": "q",
  "ԝ": "w",
  "ա": "a",
  "զ": "q",
  "ժ": "d",
  "հ": "h",
  "ո": "n",
  "ս": "u",
  "ց": "g",
  "ք": "p",
  "օ": "o",
  "ᴀ": "a",
  "ᴄ": "c",
  "ᴇ": "e",
  "ᴊ": "j",
  "ᴋ": "k",
  "ᴍ": "m",
  "ᴏ": "o",
  "ᴘ": "p",
  "ᴛ": "t",
  "ᴜ": "u",
  "ᴠ": "v",
  "ᴡ": "w",
  "ᴢ": "z",
  "ℓ": "l",
  "ℯ": "e",
  "ℴ": "o",
  "ⅰ": "i",
  "ⅴ": "v",
  "ⅹ": "x",
  "ⅼ": "l",
  "ⅽ": "c",
  "ⅾ": "d",
  "ⅿ": "m",
  "ꜱ": "s",
  "ꝺ": "d",
  "ꞵ": "b",
  "ꬲ": "e",
  "ｅ": "e"
 },
 "context_tokens": [
  "974",
  "arab",
  "bank",
  "doha",
  "gcc",
  "gov",
  "gulf",
  "online",
  "pay",
  "qa",
  "qatar",
  "qatari"
 ],
 "embedded_tld_tokens": [
  "com",
  "gov",
  "net",
  "org",
  "qa"
 ],
 "free_ca_markers": [
  "let's encrypt",
  "letsencrypt",
  "zerossl",
  "buypass",
  "google trust services"
 ],
 "generation_combos": [
  "login",
  "secure",
  "verify",
  "online",
  "account",
  "update",
  "support",
  "portal",
  "bank",
  "pay",
  "app",
  "mobile",
  "qa",
  "qatar",
  "974",
  "otp",
  "card",
  "service",
  "help",
  "official"
 ],
 "global_brands": [
  "adobe",
  "amazon",
  "americanexpress",
  "apple",
  "aramex",
  "binance",
  "chase",
  "citibank",
  "coinbase",
  "dhl",
  "docusign",
  "dropbox",
  "facebook",
  "fedex",
  "gmail",
  "google",
  "hsbc",
  "icloud",
  "instagram",
  "linkedin",
  "mastercard",
  "metamask",
  "microsoft",
  "netflix",
  "office365",
  "onedrive",
  "outlook",
  "paypal",
  "sharepoint",
  "spotify",
  "steam",
  "telegram",
  "usps",
  "wellsfargo",
  "whatsapp"
 ],
 "high_risk_tlds": [
  "accountant",
  "bar",
  "bid",
  "bond",
  "buzz",
  "cam",
  "cf",
  "cfd",
  "country",
  "cricket",
  "cyou",
  "date",
  "download",
  "faith",
  "ga",
  "gdn",
  "gq",
  "icu",
  "kim",
  "loan",
  "lol",
  "men",
  "ml",
  "mom",
  "monster",
  "mov",
  "party",
  "quest",
  "racing",
  "rest",
  "review",
  "sbs",
  "science",
  "stream",
  "surf",
  "tk",
  "trade",
  "wang",
  "win",
  "zip"
 ],
 "homoglyphs": {
  "a": [
   "à",
   "á",
   "â",
   "ä",
   "α",
   "а",
   "ạ"
  ],
  "b": [
   "d",
   "ḅ",
   "ʙ",
   "Ь"
  ],
  "c": [
   "ç",
   "ć",
   "с",
   "ϲ"
  ],
  "d": [
   "b",
   "ḍ",
   "ɗ",
   "ԁ"
  ],
  "e": [
   "è",
   "é",
   "ê",
   "ë",
   "е",
   "ẹ"
  ],
  "g": [
   "q",
   "ɡ",
   "ġ"
  ],
  "h": [
   "ḥ",
   "ħ",
   "һ"
  ],
  "i": [
   "1",
   "l",
   "í",
   "ì",
   "ï",
   "і",
   "ı"
  ],
  "k": [
   "ḳ",
   "ĸ",
   "к"
  ],
  "l": [
   "1",
   "i",
   "ł",
   "ӏ"
  ],
  "m": [
   "rn",
   "ṃ",
   "м"
  ],
  "n": [
   "ñ",
   "ṇ",
   "п"
  ],
  "o": [
   "0",
   "ó",
   "ò",
   "ö",
   "ø",
   "о",
   "ο"
  ],
  "p": [
   "ṗ",
   "р",
   "ρ"
  ],
  "q": [
   "g",
   "ԛ"
  ],
  "r": [
   "ṛ",
   "ŗ",
   "г"
  ],
  "s": [
   "5",
   "ṣ",
   "ś",
   "ş",
   "ѕ"
  ],
  "t": [
   "ṭ",
   "ţ",
   "т"
  ],
  "u": [
   "ú",
   "ù",
   "ü",
   "ū",
   "ц",
   "υ"
  ],
  "v": [
   "ṿ",
   "ν",
   "ѵ"
  ],
  "w": [
   "vv",
   "ẁ",
   "ẃ",
   "ԝ"
  ],
  "x": [
   "ẋ",
   "х",
   "χ"
  ],
  "y": [
   "ý",
   "ÿ",
   "ŷ",
   "у"
  ],
  "z": [
   "ẓ",
   "ź",
   "ż",
   "з"
  ]
 },
 "keyboard_adjacent": {
  "0": "9op",
  "1": "2q",
  "2": "13qw",
  "3": "24we",
  "4": "35er",
  "5": "46rt",
  "6": "57ty",
  "7": "68yu",
  "8": "79ui",
  "9": "80io",
  "a": "qwsz",
  "b": "vghn",
  "c": "xdfv",
  "d": "ersfxc",
  "e": "wrds",
  "f": "rtdgcv",
  "g": "tyfhvb",
  "h": "yugjbn",
  "i": "uojk",
  "j": "uihknm",
  "k": "oijlm",
  "l": "pk",
  "m": "njk",
  "n": "bhjm",
  "o": "iplk",
  "p": "ol",
  "q": "wa",
  "r": "etdf",
  "s": "weadxz",
  "t": "ryfg",
  "u": "yijh",
  "v": "cfgb",
  "w": "qeas",
  "x": "zsdc",
  "y": "tugh",
  "z": "asx"
 },
 "leet_generation": {
  "a": [
   "4"
  ],
  "b": [
   "8"
  ],
  "e": [
   "3"
  ],
  "g": [
   "9"
  ],
  "i": [
   "1"
  ],
  "l": [
   "1"
  ],
  "o": [
   "0"
  ],
  "s": [
   "5"
  ],
  "t": [
   "7"
  ]
 },
 "leet_map": {
  "!": "i",
  "$": "s",
  "0": "o",
  "1": "l",
  "3": "e",
  "4": "a",
  "5": "s",
  "7": "t",
  "8": "b",
  "9": "g",
  "@": "a",
  "|": "l"
 },
 "medium_risk_tlds": [
  "app",
  "asia",
  "bank",
  "best",
  "biz",
  "cash",
  "cc",
  "center",
  "click",
  "cloud",
  "club",
  "cn",
  "co",
  "credit",
  "dev",
  "digital",
  "email",
  "finance",
  "fit",
  "fun",
  "help",
  "info",
  "life",
  "link",
  "live",
  "me",
  "money",
  "one",
  "online",
  "page",
  "pics",
  "pw",
  "ru",
  "run",
  "services",
  "shop",
  "site",
  "solutions",
  "space",
  "store",
  "su",
  "support",
  "tech",
  "today",
  "top",
  "vip",
  "website",
  "work",
  "world",
  "ws",
  "xyz"
 ],
 "official_suffixes": [
  "edu.qa",
  "gov.qa",
  "mil.qa"
 ],
 "official_tokens": [
  "e-gov",
  "egov",
  "gov",
  "government",
  "govt",
  "hukoomi",
  "metrash",
  "ministry",
  "moi"
 ],
 "phishing_keywords": [
  "account",
  "accounts",
  "activate",
  "activation",
  "alert",
  "auth",
  "authenticate",
  "authentication",
  "bank",
  "banking",
  "billing",
  "bonus",
  "cashback",
  "confirm",
  "confirmation",
  "credential",
  "credentials",
  "customs",
  "delivery",
  "docusign",
  "ebanking",
  "fine",
  "fines",
  "gift",
  "giftcard",
  "helpdesk",
  "invoice",
  "kyc",
  "log-in",
  "login",
  "logon",
  "mailbox",
  "microsoft365",
  "netbanking",
  "notice",
  "office-365",
  "office365",
  "onedrive",
  "onlinebanking",
  "otp",
  "parcel",
  "passcode",
  "password",
  "payment",
  "payments",
  "pin",
  "prize",
  "promo",
  "qatar-id",
  "qatarid",
  "recover",
  "recovery",
  "refund",
  "renew",
  "renewal",
  "restrict",
  "restricted",
  "reward",
  "rewards",
  "secure",
  "security",
  "sharepoint",
  "shipment",
  "sign-in",
  "signin",
  "social-security",
  "ssn",
  "statement",
  "support",
  "suspend",
  "suspended",
  "tax-refund",
  "traffic",
  "unlock",
  "update",
  "updates",
  "urgent",
  "validate",
  "validation",
  "verification",
  "verified",
  "verify",
  "violation",
  "wallet",
  "webmail",
  "winner"
 ],
 "protected_brands": [
  "qnb.com",
  "qnb.com.qa",
  "cbq.qa",
  "dohabank.com",
  "dohabank.qa",
  "qib.com.qa",
  "alrayan.com",
  "dukhanbank.com",
  "ahlibank.com.qa",
  "qiib.com.qa",
  "qdb.qa",
  "qcb.gov.qa",
  "qfc.qa",
  "sadad.qa",
  "ooredoo.qa",
  "ooredoo.com",
  "vodafone.qa",
  "vodafone.com",
  "hukoomi.gov.qa",
  "moi.gov.qa",
  "ncsa.gov.qa",
  "qcert.org",
  "moph.gov.qa",
  "hamad.qa",
  "mcit.gov.qa",
  "moci.gov.qa",
  "km.qa",
  "ashghal.gov.qa",
  "qatarenergy.qa",
  "qatarairways.com",
  "dohahamadairport.com",
  "qpost.qa",
  "qcharity.org",
  "qrcs.org.qa",
  "snoonu.com",
  "talabat.com",
  "qu.edu.qa",
  "qf.org.qa"
 ],
 "qatar_brand_tokens": [
  "ahlibank",
  "alrayan",
  "ashghal",
  "cbq",
  "dohabank",
  "dukhan",
  "hamadairport",
  "hamadmedical",
  "himyan",
  "hmcqatar",
  "hukoomi",
  "kahramaa",
  "mcit",
  "metrash",
  "moci",
  "moiqatar",
  "moph",
  "ncsa",
  "ooredoo",
  "qatarairways",
  "qatarenergy",
  "qatarfoundation",
  "qataruniversity",
  "qcb",
  "qcert",
  "qcharity",
  "qdb",
  "qfc",
  "qib",
  "qiib",
  "qnb",
  "qpost",
  "qrcs",
  "sadad",
  "snoonu",
  "talabat",
  "vodafoneqa"
 ],
 "squat_tlds": [
  "com",
  "net",
  "org",
  "qa",
  "com.qa",
  "co",
  "info",
  "biz",
  "me",
  "io",
  "app",
  "xyz",
  "top",
  "online",
  "site",
  "icu",
  "club",
  "live",
  "shop",
  "cc",
  "link",
  "click"
 ],
 "suffixes": {
  "free_hosting": [
   "000webhostapp.com",
   "appspot.com",
   "azurestaticapps.net",
   "azurewebsites.net",
   "bio.link",
   "blob.core.windows.net",
   "blogspot.com",
   "bubbleapps.io",
   "canva.site",
   "carrd.co",
   "cloudfront.net",
   "ddns.net",
   "duckdns.org",
   "dweb.link",
   "firebaseapp.com",
   "fly.dev",
   "forms.gle",
   "framer.app",
   "framer.website",
   "github.io",
   "gitlab.io",
   "glideapp.io",
   "glitch.me",
   "godaddysites.com",
   "googleusercontent.com",
   "herokuapp.com",
   "hopto.org",
   "ipfs.dweb.link",
   "ipfs.io",
   "jimdosite.com",
   "linktr.ee",
   "loca.lt",
   "mailchimpsites.com",
   "my.canva.site",
   "my.sharepoint.com",
   "myftp.org",
   "mystrikingly.com",
   "netlify.app",
   "ngrok-free.app",
   "ngrok.app",
   "ngrok.io",
   "no-ip.org",
   "notion.site",
   "onrender.com",
   "pages.dev",
   "r2.dev",
   "railway.app",
   "repl.co",
   "replit.app",
   "s3-website.amazonaws.com",
   "s3.amazonaws.com",
   "serveo.net",
   "sharepoint.com",
   "sites.google.com",
   "softr.app",
   "square.site",
   "surge.sh",
   "sytes.net",
   "t.me",
   "telegra.ph",
   "trycloudflare.com",
   "typeform.com",
   "vercel.app",
   "web-app.com",
   "web.app",
   "web.core.windows.net",
   "webador.com",
   "webflow.io",
   "webnode.page",
   "weebly.com",
   "wixsite.com",
   "wixstudio.io",
   "wordpress.com",
   "workers.dev",
   "yolasite.com",
   "z13.web.core.windows.net",
   "zapto.org"
  ],
  "gcc_mena": [
   "ac.ae",
   "ac.ir",
   "ac.ma",
   "bel.tr",
   "co.ae",
   "co.ir",
   "co.ma",
   "com.bh",
   "com.dz",
   "com.eg",
   "com.iq",
   "com.jo",
   "com.kw",
   "com.lb",
   "com.om",
   "com.pk",
   "com.sa",
   "com.tn",
   "com.tr",
   "edu.bh",
   "edu.dz",
   "edu.eg",
   "edu.iq",
   "edu.jo",
   "edu.kw",
   "edu.lb",
   "edu.om",
   "edu.pk",
   "edu.sa",
   "edu.tr",
   "emb.kw",
   "eun.eg",
   "gov.ae",
   "gov.bh",
   "gov.dz",
   "gov.eg",
   "gov.iq",
   "gov.ir",
   "gov.jo",
   "gov.kw",
   "gov.lb",
   "gov.ma",
   "gov.om",
   "gov.pk",
   "gov.sa",
   "gov.tn",
   "gov.tr",
   "ind.kw",
   "med.om",
   "med.sa",
   "mil.ae",
   "mil.kw",
   "net.ae",
   "net.bh",
   "net.eg",
   "net.iq",
   "net.jo",
   "net.kw",
   "net.lb",
   "net.om",
   "net.pk",
   "net.sa",
   "net.tr",
   "org.ae",
   "org.bh",
   "org.eg",
   "org.iq",
   "org.ir",
   "org.jo",
   "org.kw",
   "org.lb",
   "org.ma",
   "org.om",
   "org.pk",
   "org.sa",
   "org.tn",
   "org.tr",
   "pub.sa",
   "sch.ae",
   "sch.sa"
  ],
  "global": [
   "ac.id",
   "ac.il",
   "ac.in",
   "ac.jp",
   "ac.kr",
   "ac.nz",
   "ac.th",
   "ac.uk",
   "ac.za",
   "co.id",
   "co.il",
   "co.in",
   "co.jp",
   "co.ke",
   "co.kr",
   "co.nz",
   "co.th",
   "co.tz",
   "co.ug",
   "co.uk",
   "co.za",
   "com.ar",
   "com.au",
   "com.bd",
   "com.bo",
   "com.br",
   "com.cn",
   "com.co",
   "com.do",
   "com.ec",
   "com.et",
   "com.gh",
   "com.gt",
   "com.hk",
   "com.ke",
   "com.kz",
   "com.lk",
   "com.mx",
   "com.my",
   "com.ng",
   "com.np",
   "com.pa",
   "com.pe",
   "com.ph",
   "com.pl",
   "com.pr",
   "com.py",
   "com.ru",
   "com.sg",
   "com.sv",
   "com.tw",
   "com.ua",
   "com.uy",
   "com.ve",
   "com.vn",
   "edu.ar",
   "edu.au",
   "edu.bd",
   "edu.br",
   "edu.cn",
   "edu.co",
   "edu.gh",
   "edu.hk",
   "edu.mx",
   "edu.my",
   "edu.ng",
   "edu.ph",
   "edu.pl",
   "edu.sg",
   "edu.tw",
   "edu.vn",
   "firm.in",
   "go.id",
   "go.jp",
   "go.ke",
   "go.kr",
   "go.th",
   "go.tz",
   "go.ug",
   "gob.ar",
   "gob.bo",
   "gob.do",
   "gob.ec",
   "gob.gt",
   "gob.mx",
   "gob.pa",
   "gob.pe",
   "gob.sv",
   "gob.ve",
   "gov.au",
   "gov.bd",
   "gov.br",
   "gov.cn",
   "gov.co",
   "gov.et",
   "gov.gh",
   "gov.hk",
   "gov.il",
   "gov.in",
   "gov.kz",
   "gov.lk",
   "gov.my",
   "gov.ng",
   "gov.np",
   "gov.ph",
   "gov.pl",
   "gov.pr",
   "gov.py",
   "gov.sg",
   "gov.tw",
   "gov.ua",
   "gov.uk",
   "gov.vn",
   "gov.za",
   "govt.nz",
   "gub.uy",
   "ltd.uk",
   "me.uk",
   "ne.jp",
   "ne.kr",
   "net.au",
   "net.br",
   "net.cn",
   "net.hk",
   "net.il",
   "net.in",
   "net.my",
   "net.nz",
   "net.pl",
   "net.ru",
   "net.sg",
   "net.tw",
   "net.ua",
   "net.uk",
   "net.vn",
   "nhs.uk",
   "or.id",
   "or.jp",
   "or.ke",
   "or.kr",
   "or.th",
   "org.ar",
   "org.au",
   "org.bd",
   "org.br",
   "org.cn",
   "org.hk",
   "org.il",
   "org.in",
   "org.mx",
   "org.my",
   "org.ng",
   "org.nz",
   "org.ph",
   "org.pl",
   "org.ru",
   "org.sg",
   "org.tw",
   "org.ua",
   "org.uk",
   "org.vn",
   "org.za",
   "plc.uk",
   "sch.uk",
   "web.id"
  ],
  "qatar": [
   "com.qa",
   "edu.qa",
   "gov.qa",
   "mil.qa",
   "name.qa",
   "net.qa",
   "org.qa",
   "sch.qa"
  ]
 },
 "version": "1.0.0",
 "visual_sequences": [
  [
   "rn",
   "m"
  ],
  [
   "vv",
   "w"
  ],
  [
   "cl",
   "d"
  ],
  [
   "nn",
   "m"
  ]
 ]
};})(typeof window!=='undefined'?window:globalThis);
